
services:
  - type: web
    name: digit-school-store-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MYSQL_HOST
        value: b3boiqle4acevw9dwxnj-mysql.services.clever-cloud.com
      - key: MYSQL_USER
        value: un4elnqqcku8i4kg
      - key: MYSQL_PASSWORD
        value: lWgyC4mYMB4azo2wgKk4
      - key: MYSQL_DB
        value: b3boiqle4acevw9dwxnj
      - key: MYSQL_PORT
        value: '3306'
